function CodeDefine() { 
this.def = new Array();
this.def["ert_main.cpp:IMU_Fusion_Obj"] = {file: "ert_main_cpp.html",line:27,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_cpp.html",line:41,type:"fcn"};
this.def["main"] = {file: "ert_main_cpp.html",line:78,type:"fcn"};
this.def["IMUFusionCommon_computeAngularV"] = {file: "IMU_Fusion_cpp.html",line:25,type:"fcn"};
this.def["IMU_Fusion_NED_ecompass"] = {file: "IMU_Fusion_cpp.html",line:33,type:"fcn"};
this.def["IMU_Fusio_quaternion_quaternion"] = {file: "IMU_Fusion_cpp.html",line:141,type:"fcn"};
this.def["IMU_Fus_quaternion_quaternion_o"] = {file: "IMU_Fusion_cpp.html",line:235,type:"fcn"};
this.def["IMUFusionCommon_predictOrientat"] = {file: "IMU_Fusion_cpp.html",line:255,type:"fcn"};
this.def["IMU_Fusio_quaternionBase_rotmat"] = {file: "IMU_Fusion_cpp.html",line:286,type:"fcn"};
this.def["IMU_Fusion_mrdiv"] = {file: "IMU_Fusion_cpp.html",line:319,type:"fcn"};
this.def["rt_atan2d_snf"] = {file: "IMU_Fusion_cpp.html",line:453,type:"fcn"};
this.def["IMU_Fusion_ahrsfilter_stepImpl"] = {file: "IMU_Fusion_cpp.html",line:489,type:"fcn"};
this.def["IMU_Fu_AHRSFilterBase_resetImpl"] = {file: "IMU_Fusion_cpp.html",line:886,type:"fcn"};
this.def["step"] = {file: "IMU_Fusion_cpp.html",line:956,type:"fcn"};
this.def["initialize"] = {file: "IMU_Fusion_cpp.html",line:1254,type:"fcn"};
this.def["terminate"] = {file: "IMU_Fusion_cpp.html",line:1347,type:"fcn"};
this.def["getBlockParameters"] = {file: "IMU_Fusion_cpp.html",line:1370,type:"fcn"};
this.def["IMU_Fusion_P"] = {file: "IMU_Fusion_cpp.html",line:1372,type:"var"};
this.def["setBlockParameters"] = {file: "IMU_Fusion_cpp.html",line:1376,type:"fcn"};
this.def["getRTM"] = {file: "IMU_Fusion_cpp.html",line:1383,type:"fcn"};
this.def["DW_IMU_Fusion_T"] = {file: "IMU_Fusion_h.html",line:48,type:"type"};
this.def["ExtU_IMU_Fusion_T"] = {file: "IMU_Fusion_h.html",line:55,type:"type"};
this.def["ExtY_IMU_Fusion_T"] = {file: "IMU_Fusion_h.html",line:62,type:"type"};
this.def["AHRS_AccelerometerNoise"] = {file: "IMU_Fusion_h.html",line:66,type:"var"};
this.def["d_quaternion_IMU_Fusion_T"] = {file: "IMU_Fusion_types_h.html",line:43,type:"type"};
this.def["c_fusion_internal_frames_NED__T"] = {file: "IMU_Fusion_types_h.html",line:60,type:"type"};
this.def["cell_wrap_IMU_Fusion_T"] = {file: "IMU_Fusion_types_h.html",line:77,type:"type"};
this.def["fusion_simulink_ahrsfilter_IM_T"] = {file: "IMU_Fusion_types_h.html",line:119,type:"type"};
this.def["IMU_Fusion_P"] = {file: "IMU_Fusion_data_cpp.html",line:26,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_cpp.html",line:34,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_cpp.html",line:82,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_cpp.html",line:93,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_cpp.html",line:141,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_cpp.html",line:34,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_cpp.html",line:82,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_cpp.html",line:33,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_cpp.html",line:34,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_cpp.html",line:35,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_cpp.html",line:36,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_cpp.html",line:37,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_cpp.html",line:38,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_cpp.html",line:46,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_cpp.html",line:58,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_cpp.html",line:64,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_cpp.html",line:70,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_cpp.html",line:119,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:48,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:55,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:62,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:79,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:80,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:81,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:83,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:84,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:94,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:95,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:96,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:97,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:98,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:99,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:100,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:101,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:107,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:108,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:109,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:110,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:111,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:112,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:113,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:114,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:115,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:127,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:132,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:137,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:144,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:151,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:158,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:165,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:172,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:179,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:197,type:"type"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_cpp.html"] = "../ert_main.cpp";
	this.html2Root["ert_main_cpp.html"] = "ert_main_cpp.html";
	this.html2SrcPath["IMU_Fusion_cpp.html"] = "../IMU_Fusion.cpp";
	this.html2Root["IMU_Fusion_cpp.html"] = "IMU_Fusion_cpp.html";
	this.html2SrcPath["IMU_Fusion_h.html"] = "../IMU_Fusion.h";
	this.html2Root["IMU_Fusion_h.html"] = "IMU_Fusion_h.html";
	this.html2SrcPath["IMU_Fusion_private_h.html"] = "../IMU_Fusion_private.h";
	this.html2Root["IMU_Fusion_private_h.html"] = "IMU_Fusion_private_h.html";
	this.html2SrcPath["IMU_Fusion_types_h.html"] = "../IMU_Fusion_types.h";
	this.html2Root["IMU_Fusion_types_h.html"] = "IMU_Fusion_types_h.html";
	this.html2SrcPath["IMU_Fusion_data_cpp.html"] = "../IMU_Fusion_data.cpp";
	this.html2Root["IMU_Fusion_data_cpp.html"] = "IMU_Fusion_data_cpp.html";
	this.html2SrcPath["rtGetInf_cpp.html"] = "../rtGetInf.cpp";
	this.html2Root["rtGetInf_cpp.html"] = "rtGetInf_cpp.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_cpp.html"] = "../rtGetNaN.cpp";
	this.html2Root["rtGetNaN_cpp.html"] = "rtGetNaN_cpp.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_defines_h.html"] = "../rt_defines.h";
	this.html2Root["rt_defines_h.html"] = "rt_defines_h.html";
	this.html2SrcPath["rt_nonfinite_cpp.html"] = "../rt_nonfinite.cpp";
	this.html2Root["rt_nonfinite_cpp.html"] = "rt_nonfinite_cpp.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_cpp.html","IMU_Fusion_cpp.html","IMU_Fusion_h.html","IMU_Fusion_private_h.html","IMU_Fusion_types_h.html","IMU_Fusion_data_cpp.html","rtGetInf_cpp.html","rtGetInf_h.html","rtGetNaN_cpp.html","rtGetNaN_h.html","rt_defines_h.html","rt_nonfinite_cpp.html","rt_nonfinite_h.html","rtwtypes_h.html"];
